import {
  AngularNodeAppEngine,
  createNodeRequestHandler,
  isMainModule,
  writeResponseToNodeResponse,
} from '@angular/ssr/node';
import express, { NextFunction, Request, Response } from 'express';
import { join } from 'node:path';

const browserDistFolder = join(import.meta.dirname, '../browser');

const app = express();
const angularApp = new AngularNodeAppEngine({
  allowedHosts: [
    'apnainsights.com',
    'www.apnainsights.com',
  ],
});

// Angular SSR's SSRF guard blocks any request whose Host is "localhost" or a
// private IP.  In production Render forwards the real domain name, so no
// rewrite is needed there.  For local dev (and as a safety net) we override
// the Host header to the public origin whenever the incoming host looks like
// a loopback address.
const PUBLIC_HOST = (() => {
  const origin = process.env['APP_ORIGIN'] ?? 'https://apnainsights.com';
  try { return new URL(origin).host; } catch { return 'apnainsights.com'; }
})();

const isLoopback = (host: string) =>
  host === 'localhost' ||
  host.startsWith('localhost:') ||
  host === '127.0.0.1' ||
  host.startsWith('127.0.0.1:') ||
  host === '::1';

// ── Known client-rendered routes ──────────────────────────────────────────────
// Angular SSR returns `null` for any route resolving to RenderMode.Client -
// this includes both legitimate client-only pages (auth, dashboards, splash)
// AND the catch-all `**` PageNotFound route. Without distinguishing them,
// truly-missing URLs get served with HTTP 200 (a "soft 404"), which hurts SEO.
// Anything not matching a known route below gets a real 404 status while still
// serving the SPA shell so Angular can render the PageNotFound UI.
const KNOWN_STATIC_PATHS = new Set([
  '', 'about', 'advertise', 'privacy-policy', 'terms', 'disclaimer',
  'editorial-policy', 'topics', 'search', 'challenges', 'shorts',
  'history', 'bookmarks', 'welcome', 'contact', 'splash', 'onboarding',
]);

const KNOWN_PREFIX_SEGMENTS = new Set([
  'category', 'author', 'tag', 'blog', 'shorts',
  'auth', 'admin', 'user', 'super-admin', 'sponsor',
]);

const isKnownClientRoute = (pathname: string): boolean => {
  const path = pathname.replace(/^\/+/, '').replace(/\/+$/, '');
  if (KNOWN_STATIC_PATHS.has(path)) return true;
  return KNOWN_PREFIX_SEGMENTS.has(path.split('/')[0]);
};

// Permanent slug redirects - old URL → new URL (HTTP 301 for SEO link equity transfer)
const SLUG_REDIRECTS: Record<string, string> = {
  'congress-wins-only-21-seats-in-assam-and-bengal-20-are-muslim-candidates':
    'congress-2026-assembly-election-results-assam-west-bengal-analysis',
};
app.get('/blog/:slug', (req: Request, res: Response, next: NextFunction) => {
  const target = SLUG_REDIRECTS[req.params['slug'] as string];
  if (target) return res.redirect(301, `/blog/${target}`);
  next();
});

// NOTE: /sitemap.xml is generated by api/sitemap.js (Vercel rewrites it there
// per vercel.json before requests ever reach this Express app) - that is the
// single source of truth for sitemap generation. A duplicate Express handler
// used to live here; it was unreachable in production and has been removed.
const SITE_ORIGIN = 'https://apnainsights.com';

// ── RSS Feed (/rss.xml) ───────────────────────────────────────────────────────
let rssCache: string | null = null;
let rssCachedAt = 0;
const RSS_TTL = 60 * 60 * 1000;

app.get(['/rss.xml', '/feed', '/feed.xml'], async (_req: Request, res: Response) => {
  try {
    if (rssCache && Date.now() - rssCachedAt < RSS_TTL) {
      res.setHeader('Content-Type', 'application/rss+xml; charset=utf-8');
      res.setHeader('Cache-Control', 'public, max-age=3600');
      return res.send(rssCache);
    }

    const r = await fetch(`${API_BASE}/post?limit=20`, {
      headers: { Accept: 'application/json' },
      signal: AbortSignal.timeout(8000),
    });
    const body = await r.json() as { data?: any[] };
    const posts: any[] = (body?.data ?? []).filter((p: any) => p.status === 'published' && p.title);

    const esc = (s: string) => String(s ?? '').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;');
    const strip = (s: string) => String(s ?? '').replace(/<[^>]*>/g, '').trim();

    const items = posts.map((p: any) => {
      const url  = `${SITE_ORIGIN}/blog/${esc(p.slug || p._id)}`;
      const date = new Date(p.updatedAt || p.createdAt).toUTCString();
      const desc = esc((p.description || strip(p.content || '')).slice(0, 300));
      const img  = p.featuredImage ? `<enclosure url="${esc(p.featuredImage)}" type="image/jpeg" length="0"/>` : '';
      const cats = (p.categories ?? []).map((c: string) => `<category>${esc(c)}</category>`).join('');
      return `<item><title>${esc(p.title)}</title><link>${url}</link><guid isPermaLink="true">${url}</guid><description>${desc}</description><pubDate>${date}</pubDate>${cats}${img}</item>`;
    }).join('');

    const xml = `<?xml version="1.0" encoding="UTF-8"?><rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom"><channel><title>ApnaInsights - Practical Knowledge for Everyday Life</title><link>${SITE_ORIGIN}</link><description>India's practical knowledge platform - expert guides on Technology, Career, Health and Business.</description><language>en-IN</language><lastBuildDate>${new Date().toUTCString()}</lastBuildDate><ttl>60</ttl><atom:link href="${SITE_ORIGIN}/rss.xml" rel="self" type="application/rss+xml"/>${items}</channel></rss>`;

    rssCache = xml; rssCachedAt = Date.now();
    res.setHeader('Content-Type', 'application/rss+xml; charset=utf-8');
    res.setHeader('Cache-Control', 'public, max-age=3600');
    return res.send(xml);
  } catch (err) {
    console.error('[RSS] failed:', err);
    return res.status(500).send('RSS temporarily unavailable');
  }
});

// ── News Sitemap (/news-sitemap.xml) ─────────────────────────────────────────
app.get('/news-sitemap.xml', async (_req: Request, res: Response) => {
  try {
    const r = await fetch(`${API_BASE}/post?limit=50`, {
      headers: { Accept: 'application/json' },
      signal: AbortSignal.timeout(8000),
    });
    const body = await r.json() as { data?: any[] };
    const posts: any[] = (body?.data ?? []).filter((p: any) => p.status === 'published' && p.title);

    const esc = (s: string) => String(s ?? '').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;');
    const twoDaysAgo = Date.now() - 2 * 24 * 60 * 60 * 1000;
    const recent = posts.filter((p: any) => new Date(p.createdAt).getTime() > twoDaysAgo);

    const urls = recent.map((p: any) => `
  <url>
    <loc>${SITE_ORIGIN}/blog/${esc(p.slug || p._id)}</loc>
    <news:news>
      <news:publication><news:name>ApnaInsights</news:name><news:language>en</news:language></news:publication>
      <news:publication_date>${new Date(p.createdAt).toISOString()}</news:publication_date>
      <news:title>${esc(p.title)}</news:title>
    </news:news>
  </url>`).join('');

    const xml = `<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:news="http://www.google.com/schemas/sitemap-news/0.9">${urls}</urlset>`;

    res.setHeader('Content-Type', 'application/xml');
    res.setHeader('Cache-Control', 'public, max-age=1800');
    return res.send(xml);
  } catch (err) {
    console.error('[News sitemap] failed:', err);
    return res.status(500).send('News sitemap temporarily unavailable');
  }
});

// ── 301 redirect: /blog/:objectId  →  /blog/:slug ─────────────────────────────
// Prevents duplicate-content indexing of old MongoDB ObjectId URLs.
const OBJECT_ID_RE = /^[0-9a-f]{24}$/i;
const API_BASE = process.env['API_URL'] ?? 'https://apnablogserver.onrender.com/api';

app.get('/blog/:id', async (req: Request, res: Response, next: NextFunction) => {
  const id = String(req.params['id'] ?? '');
  if (!OBJECT_ID_RE.test(id)) return next(); // already a slug - let SSR handle it

  try {
    const apiRes = await fetch(`${API_BASE}/post/${id}`, {
      headers: { Accept: 'application/json' },
      signal: AbortSignal.timeout(10000),
    });
    if (!apiRes.ok) return next();

    const body = await apiRes.json() as { data?: { slug?: string } };
    const slug = body?.data?.slug;
    if (slug && slug !== id) {
      return res.redirect(301, `/blog/${slug}`);
    }
  } catch {
    // API down or timeout - fall through to SSR so the page still loads
  }
  return next();
});

/**
 * Example Express Rest API endpoints can be defined here.
 * Uncomment and define endpoints as necessary.
 *
 * Example:
 * ```ts
 * app.get('/api/{*splat}', (req, res) => {
 *   // Handle API request
 * });
 * ```
 */

// /contact → /about (server-side 301 so bots follow without JavaScript)
app.get('/contact', (_req: Request, res: Response) => {
  res.redirect(301, '/about');
});

/**
 * Serve static files from /browser
 */
app.use(
  express.static(browserDistFolder, {
    maxAge: '1y',
    index: false,
    redirect: false,
  }),
);

// A request for a path that looks like a static asset (has a static file
// extension) but wasn't served by express.static above doesn't exist -
// bots/scanners probing for .map/.env-lookalikes/etc. shouldn't trigger a
// full SSR render (which itself makes a backend API call) just to 404.
const STATIC_EXT_RE = /\.(?:js|css|map|json|txt|png|jpe?g|gif|svg|ico|webp|avif|woff2?|ttf|eot|xml)$/i;
app.use((req, res, next) => {
  if (STATIC_EXT_RE.test(req.path)) {
    res.status(404).type('text/plain').send('Not found');
    return;
  }
  next();
});

// Cache-Control overrides for SSR (RenderMode.Server) routes - Angular's own
// default header on these Function responses wins over vercel.json's static
// header rules, so the intended CDN caching for these routes never actually
// applies unless we set it here explicitly.
const SSR_CACHE_RULES: [string, string][] = [
  ['/blog/',   'public, s-maxage=120, stale-while-revalidate=86400'],
  ['/author/', 'public, s-maxage=300, stale-while-revalidate=86400'],
  ['/tag/',    'public, s-maxage=600, stale-while-revalidate=86400'],
];

/**
 * Handle all other requests by rendering the Angular application.
 */
app.use((req, res, next) => {
  // Rewrite loopback Host headers so Angular SSR's SSRF guard allows the
  // request. Production requests (Host: apnainsights.com) pass through as-is.
  if (isLoopback(req.headers['host'] ?? '')) {
    req.headers['host'] = PUBLIC_HOST;
  }

  angularApp
    .handle(req)
    .then((response) => {
      if (!response) {
        // RenderMode.Client route - Angular returns null, serve the SPA shell.
        // Unknown URLs (the `**` PageNotFound route) get a real 404 status.
        if (!isKnownClientRoute(req.path)) {
          return res.status(404).sendFile(join(browserDistFolder, 'index.html'));
        }
        return res.sendFile(join(browserDistFolder, 'index.html'));
      }

      const cacheRule = SSR_CACHE_RULES.find(([prefix]) => req.path.startsWith(prefix));
      if (cacheRule && response.status < 300) {
        response.headers.set('Cache-Control', cacheRule[1]);
      }

      // If Angular SSR failed (e.g. backend cold-start timeout), distinguish
      // between bot and browser traffic:
      //  • Bots/crawlers (Googlebot, AdSense) get a 503 + Retry-After so they
      //    retry later rather than caching an empty page as "low value content".
      //  • Real browsers get the client shell so Angular can bootstrap and
      //    fetch the data itself - user experience is preserved.
      if (response.status >= 500) {
        console.warn(`SSR returned ${response.status} for ${req.url}`);
        const ua = (req.headers['user-agent'] ?? '').toLowerCase();
        const isBot = /googlebot|adsbot|mediapartners|bingbot|yandex|duckduckbot|slurp|baiduspider|facebookexternalhit|twitterbot|rogerbot|linkedinbot|embedly|quora|pinterest|slackbot|vkshare|outbrain|facebot|ia_archiver/.test(ua);
        if (isBot) {
          res.setHeader('Retry-After', '60');
          res.status(503).send(
            '<!doctype html><html lang="en"><head><meta charset="utf-8"><title>ApnaInsights - Service Temporarily Unavailable</title></head>' +
            '<body><h1>503 Service Temporarily Unavailable</h1><p>ApnaInsights is starting up. Please try again in a moment.</p></body></html>'
          );
          return;
        }
        res.sendFile(join(browserDistFolder, 'index.html'));
        return;
      }

      return writeResponseToNodeResponse(response, res);
    })
    .catch(next);
});

/**
 * When Angular SSR throws (e.g. API timeout during render), apply the same
 * bot/browser split: bots get 503 so they retry; browsers get the SPA shell.
 */
app.use((err: unknown, req: Request, res: Response, _next: NextFunction) => {
  console.error('SSR render error:', err);
  const ua = (req.headers['user-agent'] ?? '').toLowerCase();
  const isBot = /googlebot|adsbot|mediapartners|bingbot|yandex|duckduckbot|slurp|baiduspider|facebookexternalhit|twitterbot|rogerbot|linkedinbot|embedly|quora|pinterest|slackbot|vkshare|outbrain|facebot|ia_archiver/.test(ua);
  if (isBot) {
    res.setHeader('Retry-After', '60');
    res.status(503).send(
      '<!doctype html><html lang="en"><head><meta charset="utf-8"><title>ApnaInsights - Service Temporarily Unavailable</title></head>' +
      '<body><h1>503 Service Temporarily Unavailable</h1><p>ApnaInsights is starting up. Please try again in a moment.</p></body></html>'
    );
    return;
  }
  res.sendFile(join(browserDistFolder, 'index.html'));
});

/**
 * Start the server if this module is the main entry point, or it is ran via PM2.
 * The server listens on the port defined by the `PORT` environment variable, or defaults to 4000.
 */
if (isMainModule(import.meta.url) || process.env['pm_id']) {
  const port = process.env['PORT'] || 4000;
  app.listen(port, (error) => {
    if (error) {
      throw error;
    }
  });
  // NOTE: Do NOT add a setInterval keepalive here.
  // On Vercel (serverless), this function process is killed after each request -
  // any interval set here never fires. Use an external uptime monitor (e.g.
  // UptimeRobot free tier) to ping the Render backend every 5 minutes instead.
}

/**
 * Request handler used by the Angular CLI (for dev-server and during build) or Firebase Cloud Functions.
 */
export const reqHandler = createNodeRequestHandler(app);
